name: Deploy to GitHub Pages

on:
  push:
    branches: [main] # or master

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: "./restaurants" # Update this to your folder's name

  deploy:
    needs: build-and-deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
